### PR TITLE
Made the Footer year live.

### PR DESCRIPTION
**Pull request by homewardgamer**
Made the footer year live through a simple javascript line. It will now automatically update in the upcoming years.

### CODE REVIEW

**Comment by homewardgamer** [comment]
@chirag-goel360
Any reviews?

**Comment by chirag-goel360** [comment]
Thanks

**Comment by homewardgamer** [comment]
Please add `hactoberfest-accepted` tag too @chirag-goel360

**Comment by chirag-goel360** [comment]
Sure 😊

**Pull request merged**
